import React from 'react';
import { Layout } from 'antd';
import Header from './components/Header';
import Footer from './components/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import './page.css';
import Carousels from './components/Carousel';
import { arrImageSlide } from './constant/home-carousel';


const layoutStyle = {
  borderRadius: 8,
  overflow: 'hidden',
  width: 'calc(50% - 8px)',
  maxWidth: 'calc(50% - 8px)',
};

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <Carousels arrImg={arrImageSlide} />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
